### ISSUE TITLE
how to manually install the sdk?

### ISSUE THREAD

**Issue by relsirc** [yahoojapan/yjlogin-ios-sdk#1]
How do I manually install the SDK? I don't want to use carthage but I do have cocoapods.

**Comment by kazuki229** [comment]
@relsirc 
Thank you for your feedback!
We will support Cocoapods, so please wait for implementation.

**Comment by relsirc** [comment]
thanks for the reply. I would also suggest updating the read me a bit. To include the format of the code challenge so people can run the sample app. :)

**Comment by kazuki229** [comment]
@relsirc 
I want the codeChallenge to be generated on the server side, I don't intentionally write the generation logic.
However, I think it is good to write the codeChallenge format, so I will modify the documentation.

**Comment by koi-tan** [comment]
I made a mistake, I will reopen

**Comment by kazuki229** [comment]
@relsirc 
I apologize for the delay in responding.
CocoaPods support is now available, so please use it.

You can use it by writing the Podfile as follows and running `pod install`.
```
platform :ios, '10.0'
use_frameworks!

target 'Your Target Name' do
    pod 'YJLoginSDK',  '~> 0.1'
end
```
