### ISSUE TITLE
Xcode12.5でビルドするとiOS14.5でクラッシュする

### ISSUE THREAD

**Issue by ShoheiSugawa-LS** [yahoojapan/yjlogin-ios-sdk#12]
### 概要
- Xcode12.5 (Swift5.4)でビルドすると、iOS14.5のシミュレーターと実機でクラッシュします
  - iOS14.5未満はクラッシュしない
- Xcode12.4 (Swift5.3)でビルドした場合は、iOSのバージョンに関係なく動作します
- AppleのDeveloperForumに同様の内容がありました
  - https://developer.apple.com/forums/thread/679251

### 環境
Cocoapodsでv1.0.0をインストール

### クラッシュログ
```
[AuthenticationSession] The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20422fba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48
	2   AuthenticationServices              0x00007fff4aae1b15 -[ASWebAuthenticationSession initWithURL:callbackURLScheme:usingEphemeralSession:completionHandler:] + 684
	3   YJLoginSDK                          0x0000000114c9cab0 $sSo26ASWebAuthenticationSessionC3url17callbackURLScheme17completionHandlerAB10Foundation3URLV_SSSgyAHSg_s5Error_pSgtctcfcTO + 272
	4   YJLoginSDK                          0x0000000114c9bc7a $sSo26ASWebAuthenticationSessionC3url17callbackURLScheme17completionHandlerAB10Foundation3URLV_SSSgyAHSg_s5Error_pSgtctcfC + 74
```
`callbackScheme:`に`yj-xxxxx:/`の形式のStringを渡していると思いますが、`:/`を抜いた場合は、Xcode12.5でiOSバージョンに関わらずクラッシュせず動作しました
https://github.com/yahoojapan/yjlogin-ios-sdk/blob/814780a6855181c365b224a3250512d32d9ef0ed/YJLoginSDK/AuthenticationProcess.swift#L146

**Comment by kazuki229** [comment]
@ShoheiSugawa-LS 
ご報告ありがとうございます、こちら確認して対応いたします。

**Comment by kazuki229** [comment]
@ShoheiSugawa-LS 
遅くなりましたがこちらの問題に対応したバージョンをリリースいたしました。
https://github.com/yahoojapan/yjlogin-ios-sdk/releases/tag/1.1.0

本issueはクローズいたします。
お知らせいただきありがとうございました:pray:

**Comment by ShoheiSugawa-LS** [comment]
ご対応いただきありがとうございました！
