### ISSUE TITLE
Implicit imports of UIKit

### ISSUE THREAD

**Issue by rsahara** [yahoojapan/yjlogin-ios-sdk#8]
Is there a reason that `YJLoginSDK.h` imports UIKit?
```
#import <UIKit/UIKit.h>
```

I think this library could be a pure Swift library by removing this import and directly importing UIKit in the Swift codes that need it (by replacing `import Foundation` with `import UIKit`).
Without the implicit imports, the library would be easier to build with build systems like Bazel.

**Comment by kazuki229** [comment]
@rsahara 
Sorry for the delay. Since this SDK depends on UIKit, `YJLoginSDK.h` imports UIKit (LoginButton, UserAgent, etc.).

**Comment by rsahara** [comment]
Yes I know. I mean using a header just for importing UIKit can be avoided since it's a Swift library.
Anyway it's not a big deal. Thanks for considering.
